package response;

public class GeoCodeGoogle {

	public static String goeCodeResponse(){
		String resp="{\r\n   \"results\" : [\r\n      {\r\n         \"address_components\" : [\r\n            {\r\n               \"long_name\" : \"1600\",\r\n               \"short_name\" : \"1600\",\r\n               \"types\" : [ \"street_number\" ]\r\n            },\r\n            {\r\n               \"long_name\" : \"Amphitheatre Parkway\",\r\n               \"short_name\" : \"Amphitheatre Pkwy\",\r\n               \"types\" : [ \"route\" ]\r\n            },\r\n            {\r\n               \"long_name\" : \"Mountain View\",\r\n               \"short_name\" : \"Mountain View\",\r\n               \"types\" : [ \"locality\", \"political\" ]\r\n            },\r\n            {\r\n               \"long_name\" : \"Santa Clara County\",\r\n               \"short_name\" : \"Santa Clara County\",\r\n               \"types\" : [ \"administrative_area_level_2\", \"political\" ]\r\n            },\r\n            {\r\n               \"long_name\" : \"California\",\r\n               \"short_name\" : \"CA\",\r\n               \"types\" : [ \"administrative_area_level_1\", \"political\" ]\r\n            },\r\n            {\r\n               \"long_name\" : \"United States\",\r\n               \"short_name\" : \"US\",\r\n               \"types\" : [ \"country\", \"political\" ]\r\n            },\r\n            {\r\n               \"long_name\" : \"94043\",\r\n               \"short_name\" : \"94043\",\r\n               \"types\" : [ \"postal_code\" ]\r\n            }\r\n         ],\r\n         \"formatted_address\" : \"1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA\",\r\n         \"geometry\" : {\r\n            \"location\" : {\r\n               \"lat\" : 37.422593,\r\n               \"lng\" : -122.0853986\r\n            },\r\n            \"location_type\" : \"ROOFTOP\",\r\n            \"viewport\" : {\r\n               \"northeast\" : {\r\n                  \"lat\" : 37.4239419802915,\r\n                  \"lng\" : -122.0840496197085\r\n               },\r\n               \"southwest\" : {\r\n                  \"lat\" : 37.4212440197085,\r\n                  \"lng\" : -122.0867475802915\r\n               }\r\n            }\r\n         },\r\n         \"place_id\" : \"ChIJ2eUgeAK6j4ARbn5u_wAGqWA\",\r\n         \"plus_code\" : {\r\n            \"compound_code\" : \"CWF7+2R Mountain View, California, United States\",\r\n            \"global_code\" : \"849VCWF7+2R\"\r\n         },\r\n         \"types\" : [ \"street_address\" ]\r\n      }\r\n   ],\r\n   \"status\" : \"OK\"\r\n}";
		return resp;
	}
}
